name: openrouter-multimodal-proxy
services:
  openrouter-multimodal-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oproxy
    image: openrouter-multimodal-proxy
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/data
    env_file:
      - ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
