version: '3.8'

services:
  openrouter-multimodal-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oproxy
    image: openrouter-multimodal-proxy
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env # Mount your actual .env file
      - ./data:/data
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      # Add other environment variables from your .env file as needed
      - DEFAULT_TEXT_MODEL=${DEFAULT_TEXT_MODEL:-openai/gpt-3.5-turbo}
      - VISION_MODEL=${VISION_MODEL:-mistralai/mistral-small-3.1-24b-instruct}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-/data/router.log.json}
      - DATABASE_URL=${DATABASE_URL:-sqlite+aiosqlite:////data/openrouter-multimodal-proxy.db}
      # OPENROUTER_REFERER=${OPENROUTER_REFERER}
      # OPENROUTER_X_TITLE=${OPENROUTER_X_TITLE}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
